on:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches:
            - "master"
        tags:
            - "**"

name: "Continuous Integration"

jobs:
    build:
        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                java-version:
                    - "11"

        name: "Java ${{ matrix.java-version }}"
        steps:
            - uses: "actions/checkout@v2"

            - uses: "actions/cache@v1"
              with:
                  path: "~/.m2/repository"
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: "Setup java"
              uses: "actions/setup-java@v1"
              with:
                  java-version: ${{ matrix.java-version }}

            - name: "Configure Git user"
              run: |
                  git config user.email "actions@github.com"
                  git config user.name "GitHub Actions"

            - name: "mvn release"
              run: "mvn --batch-mode release:prepare release:perform"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
