on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - "master"
    tags:
      - "**"

name: "Continuous Integration"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
    - uses: "actions/checkout@v2"
    - name: "Setup JDK 11"
      uses: "actions/setup-java@v2"
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

          #- name: "Configure Git user"
          #  run: |
          #      git config user.email "actions@github.com"
          #      git config user.name "GitHub Actions"
    - name: "Build with Gradle"
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: "Publish with Gradle"
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publish
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
